advcbv/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
urlpatterns = [
    path('',views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls',namespace='basic_app'))
]

basic_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    url(r'^(?P<pk>[-\w]+)/$',views.SchoolDetailView.as_view(),name='detail'),
    # path('detail',views.SchoolDetailView.as_view(),name='anotherdetail')

]

basic_app/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.DO_NOTHING,)

    def __str__(self):
        return self.name

basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView
from django.http import HttpResponse
from . import models
# Create your views here.
# def index(request):
#     return render(request,"basic_app/index.html")

# class CBView(View):
#     def get(self,request):
#         return HttpResponse('Class based views are cool!')

class IndexView(TemplateView):
    template_name = "basic_app/index.html"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'BASIC INJECTION!'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    #school_list automatically created by django if not specified and sent to templates(lower cases the model name and adds _list)

class SchoolDetailView(DetailView):
    context_object_name = "school_detail"
    model = models.Student
    template_name = "basic_app/school_detail.html"
    #detail view just lowercases the model name and returns the context

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}



<div class="container">
  <div class="jumbotron">
    <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
      <div class="card-header">Welcome to the School Detail Page!</div>
      <div class="card-body">
      <h5 class="card-title">School Details:</h5>
      <p class="card-text"><strong>Name:{{ school_detail.name }}</strong></p>
      <p class="card-text"><strong>Principal:</strong>{{ school_detail.principal }}</p>
      <p class="card-text"><strong>Location</strong>{{ school_detail.location }}</p>
      <h3>Students:</h3>
      {% for student in school_detail.students.all %}
        <p class="card-text">{{student.name}} who is {{student.age}} years old</p>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>

<div class="container">
  <div class="list-group">
    {% for school in schools %}
    <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"><a href="{{school.id}}">{{ school.name }}</a></h5>
      <small>{{ school.location }}</small>
    </div>
    <p class="mb-1"><strong>Principal:</strong>{{ school.principal }}
    </a>
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BASE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Home Page!</h1>
  </div>
{% endblock %}